# Generated by Django 5.0b1 on 2023-10-27 09:59

from django.db import migrations


def take_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoes')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    all_unique_brands = shoe.objects.values_list('brand', flat=True).distinct()

    unique_brands_to_take = [unique_brands(brand_name=brand_name) for brand_name in all_unique_brands]

    unique_brands.objects.bulk_create(unique_brands_to_take)


def unique_brands_delete(apps, schema_editor):
    unique_brands = apps.get_model('main', 'UniqueBrands')

    unique_brands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(take_unique_brands, reverse_code=unique_brands_delete)
    ]
