# Generated by Django 5.0a1 on 2023-10-22 17:01
import random

from django.db import migrations


def add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    products = Product.objects.all()
    all_barcodes = random.sample(range(10000, 100000), len(products))

    for i in range(len(products)):
        products[i].barcode = all_barcodes[i]
        products[i].save()


def reverse_barcode_add(apps, schema_editor):
    print("Reverse barcode add")


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=reverse_barcode_add)
    ]
