# Generated by Django 5.0a1 on 2023-10-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20231022_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
