# Generated by Django 5.0a1 on 2023-10-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_barcode'),
        ('main_app', '0004_auto_20231022_1926'),
    ]

    operations = [
    ]
